customCommands:
  - key: "<a-c>"
    context: "files"
    description: "commit with commitizen (native UI)"
    prompts:
      - type: "menu"
        title: "Select the type of change you are committing"
        key: "Type"
        options:
          - name: "feat"
            description: "A new feature"
            value: "feat"
          - name: "fix"
            description: "A bug fix"
            value: "fix"
          - name: "docs"
            description: "Documentation only changes"
            value: "docs"
          - name: "style"
            description: "Changes that do not affect the meaning of the code"
            value: "style"
          - name: "refactor"
            description: "A code change that neither fixes a bug nor adds a feature"
            value: "refactor"
          - name: "perf"
            description: "A code change that improves performance"
            value: "perf"
          - name: "test"
            description: "Adding missing tests or correcting existing tests"
            value: "test"
          - name: "build"
            description: "Changes that affect the build system or dependencies"
            value: "build"
          - name: "ci"
            description: "Changes to our CI configuration files and scripts"
            value: "ci"
          - name: "chore"
            description: "Other changes that don't modify src or test files"
            value: "chore"
          - name: "revert"
            description: "Reverts a previous commit"
            value: "revert"
      - type: "input"
        title: "Scope of this change (class/file)? [optional]"
        key: "Scope"
      - type: "input"
        title: "Short, imperative summary (no period):"
        key: "Description"
      - type: "input"
        title: "Provide additional context/body: [optional]"
        key: "Body"
      - type: "menu"
        title: "Is this a BREAKING CHANGE? (MAJOR in SemVer)"
        key: "isBreaking"
        options:
          - name: "No"
            description: "Not a breaking change"
            value: ""
          - name: "Yes"
            description: "Yes, this breaks compatibility"
            value: "!"
      - type: "input"
        title: "Footer: Breaking changes & closed issues [optional]"
        key: "Footer"
    command: >-
      git commit 
      -m "{{.Form.Type}}{{if .Form.Scope}}({{.Form.Scope}}){{end}}{{.Form.isBreaking}}: {{.Form.Description}}"
      {{if .Form.Body}} -m "{{.Form.Body}}" {{end}}
      {{if .Form.Footer}} -m "{{.Form.Footer}}" {{end}}

  - key: "<a-r>"
    context: "global"
    description: "Create Release (Bump version, Changelog, Tag)"
    command: "npx commit-and-tag-version"
    output: terminal
