# Base16 oomox-rocha_theme - kitty color config
# Scheme by oomox-rocha_theme
background #000000
foreground #19cb00
selection_background #19cb00
selection_foreground #000000
url_color #000000
cursor #19cb00
cursor_text_color #000000
active_border_color #0c6500
inactive_border_color #301e1e
active_tab_background #000000
active_tab_foreground #19cb00
inactive_tab_background #301e1e
inactive_tab_foreground #000000
tab_bar_background #301e1e
wayland_titlebar_color #000000
macos_titlebar_color #000000

# normal
color0 #000000
color1 #f2201f
color2 #23fd00
color3 #fffd00
color4 #1a8fff
color5 #fd20ff
color6 #14ffff
color7 #19cb00

# bright
color8 #0c6500
color9 #cecb00
color10 #301e1e
color11 #907e7e
color12 #000000
color13 #dddddd
color14 #cc6100
color15 #ffffff
